--Only to DROP tables
--make sure tables are already empty
DROP TABLE AreaSellsProduct CASCADE CONSTRAINTS;
DROP TABLE RepSellsProduct CASCADE CONSTRAINTS;
DROP TABLE RepSellsArea CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Area CASCADE CONSTRAINTS;
DROP TABLE Rep CASCADE CONSTRAINTS;
