--This is only to practice DDL commands

--CREATING Rep Table

CREATE TABLE Rep(
    RID NUMBER PRIMARY KEY,
    RNAME VARCHAR2(40),
    RAGE NUMBER,
    SALARY NUMBER(12,2)
);

--CREATING AREA TABLE

CREATE TABLE Area(
    ARID VARCHAR2(10) PRIMARY KEY,
    ANAME VARCHAR2(40),
    CITY VARCHAR(20),
    BUDGET NUMBER(10,2)
);

--CREATING PRODUCT TABLE
CREATE TABLE Product(
    PRID NUMBER PRIMARY KEY,
    PNAME VARCHAR2(40),
    PDESC VARCHAR2(150),
    PRICE NUMBER(5,2)
);

--CREATING REPSELLSAREA TABLE
CREATE TABLE RepSellsArea(
    RID NUMBER,
    ARID VARCHAR2(10),
    HOURS NUMBER,
    PRIMARY KEY(RID,ARID),
    REVENUE NUMBER(10,2),
    FOREIGN KEY (RID) REFERENCES Rep(RID),
    FOREIGN KEY (ARID) REFERENCES Area(ARID)
);

--CREATING REPSELLSPRODUCT TABLE
CREATE TABLE RepSellsProduct(
    RID NUMBER,
    PRID NUMBER,
    HOURS NUMBER,
    REVENUE NUMBER(10,2),
    PRIMARY KEY(RID,PRID),
    FOREIGN KEY (RID) REFERENCES Rep(RID),
    FOREIGN KEY (PRID) REFERENCES Product(PRID)
);

--CREATING AREASELLSPRODUCT
CREATE TABLE AREASELLSPRODUCT(
    ARID VARCHAR2(10),
    PRID NUMBER,
    HOURS NUMBER,
    REVENUE NUMBER(10,2),
    PRIMARY KEY(ARID,PRID),
    FOREIGN KEY(ARID) REFERENCES Area(ARID),
    FOREIGN KEY(PRID) REFERENCES Product(PRID)
);

